# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/df61b93b-db18-4a34-94a0-23919209db48";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0E24-CC5B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/hdd" =
    { device = "/dev/disk/by-uuid/aa661c52-b9f6-4886-ba09-e15121272557";
      fsType = "ext4";
      options = [ "nofail" ];
    };

  fileSystems."/home/ayush/Desktop" =
    { device = "/mnt/hdd/Desktop";
      options = [ "bind" ];
    };

  fileSystems."/home/ayush/Downloads" =
    { device = "/mnt/hdd/Downloads";
    options = [ "bind" ];
    };

  fileSystems."/home/ayush/Documents" =
    { device = "/mnt/hdd/Documents";
      options = [ "bind" ];
    };

  fileSystems."/home/ayush/Music" =
    { device = "/mnt/hdd/Music";
    options = [ "bind" ];
    };

  fileSystems."/home/ayush/Pictures" =
    { device = "/mnt/hdd/Pictures";
      options = [ "bind" ];
    };

  fileSystems."/home/ayush/Videos" =
    { device = "/mnt/hdd/Videos";
    options = [ "bind" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/408760e9-ab5e-4841-b644-d483b678e897"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
